---
# $Author$
# $Date$
# $Source$

- name: Dump the variables / facts known by Ansible for the Logrotate role
  include_role:
    name: mdrotthoff.ansible-debug

- name: Install the logrotate package
  package:
    name: logrotate
    state: present
  when: logrotate_scripts is defined and logrotate_scripts|length > 0

- name: Setup logrotate.d scripts provided
  template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
  with_items: "{{ logrotate_scripts }}"
  when: logrotate_scripts is defined
