---
#- name: Print some debug information 
#  vars: 
#    msg: |
#        Module Variables ("vars"):
#        --------------------------------
#        {{ vars | to_nice_json }} 
#
#        Environment Variables ("environment"):
#        --------------------------------
#       {{ environment | to_nice_json }} 
#
#        GROUP NAMES Variables ("group_names"):
#        --------------------------------
#        {{ group_names | to_nice_json }}
#
#        GROUPS Variables ("groups"):
#        --------------------------------
#        {{ groups | to_nice_json }}
#
#        HOST Variables ("hostvars"):
#        --------------------------------
#        {{ hostvars | to_nice_json }} 

#  debug: 
#    msg: "{{ msg.split('\n') }}"

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags: debug_info

- name: Display the length of logrotate_scripts
  debug:
    var: logrotate_scripts|length
  when: logrotate_scripts is defined

- name: Install the logrotate package
  package:
    name: logrotate
    state: present
  when: logrotate_scripts is defined and logrotate_scripts|length > 0

- name: Setup logrotate.d scripts provided
  template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
  with_items: "{{ logrotate_scripts }}"
  when: logrotate_scripts is defined
